Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -65,6 +65,12 @@ jobs:
         run: |
           google-chrome --version
           chromedriver --version
+
+      - name: Run Script with Debugging
+        run: |
+          set -x  # Enable debugging output
+          python3 Unborn.py || echo "Python script exited with error code $?"
+        shell: bash
           
       - name: Run Unborn Script
         run: | 
